version: '3.7'

services:

  mongo:
    container_name: bakeryStoreDB
    image: bsmongoimage
    restart: on-failure
    volumes: 
      - d:/dataFromMongo/bakeryStoreData:/sharedData
      - volume1:/data/db
    command: [--auth]
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

volumes:

  volume1:
    name: bakeryStoreDB