version: '3.7'

services:

  mongo:
    # el uso de la imagen bakeryStoreDB es opcional simplemente
    # se podria usar la imagen oficial de mongo
    container_name: bakeryStoreDB
    image: bsmongoimage
    restart: on-failure
    volumes: 
      # puedes cambiar d:/dataFromMongo con cualquier path de tu servidor
      - d:/dataFromMongo/bakeryStoreData:/sharedData 
      - volume1:/data/db
    command: [--auth]
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

volumes:

  volume1:
    name: bakeryStoreDB